pool:
  name: SelfHosted
trigger:
  - master
   
steps: 
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'
  inputs:
     SourceFolder: deployment
     Contents: '*.json'
     TargetFolder: '$(build.artifactstagingdirectory)/Templates'